version: "3.8"

services: 
    bzzzer:
        image: eclipse-mosquitto
        ports:
            - "9001:9001"
            - "1883:1883"
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf